add_executable(arcology_os_tests arcology-os/tests/unit/arcology_os_tests.cpp)
target_link_libraries(arcology_os_tests PRIVATE arcology_os)
add_test(NAME arcology_os_unit_tests COMMAND arcology_os_tests)

arco_add_script_test(
    systems_fixed_width_types_smoke
    arcology-os/tests/systems/systems_fixed_width_types_smoke.sh
    $<TARGET_FILE:ArcoFission>
)
arco_add_script_test(
    systems_freestanding_profile_smoke
    arcology-os/tests/systems/systems_freestanding_profile_smoke.sh
    $<TARGET_FILE:ArcoFission>
)
arco_add_script_test(
    systems_amir_primitives_smoke
    arcology-os/tests/systems/systems_amir_primitives_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_frontend_amir_contract_smoke
    arcology-os/tests/systems/systems_frontend_amir_contract_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_hardware_semantics_smoke
    arcology-os/tests/systems/systems_hardware_semantics_smoke.sh
    $<TARGET_FILE:ArcoFission>
)
arco_add_script_test(
    systems_calling_convention_smoke
    arcology-os/tests/systems/systems_calling_convention_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_uefi_bindings_smoke
    arcology-os/tests/systems/systems_uefi_bindings_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_utf16_encoding_smoke
    arcology-os/tests/systems/systems_utf16_encoding_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_x86_64_codegen_smoke
    arcology-os/tests/systems/systems_x86_64_codegen_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_pe_image_smoke
    arcology-os/tests/systems/systems_pe_image_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_qemu_ovmf_harness_smoke
    arcology-os/tests/systems/systems_qemu_ovmf_harness_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arcology_hardware_artifact_smoke
    arcology-os/tests/systems/systems_arcology_hardware_artifact_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_integer_core_smoke
    arcology-os/tests/systems/systems_integer_core_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_control_flow_smoke
    arcology-os/tests/systems/systems_control_flow_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_port_io_smoke
    arcology-os/tests/systems/systems_port_io_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_memory_address_smoke
    arcology-os/tests/systems/systems_memory_address_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_gop_discovery_smoke
    arcology-os/tests/systems/systems_gop_discovery_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_blockio_discovery_smoke
    arcology-os/tests/systems/systems_blockio_discovery_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_runtime_handle_abi_smoke
    arcology-os/tests/systems/systems_runtime_handle_abi_smoke.sh
    $<TARGET_FILE:arco_cli>
    ${CMAKE_CURRENT_SOURCE_DIR}
    $<TARGET_FILE:ArcoFission>
)
arco_add_script_test(
    systems_arco_basic_substrate_smoke
    arcology-os/tests/systems/systems_arco_basic_substrate_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_primitives_smoke
    arcology-os/tests/systems/systems_arco_basic_primitives_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_color_smoke
    arcology-os/tests/systems/systems_arco_basic_color_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_memory_manager_smoke
    arcology-os/tests/systems/systems_arco_basic_memory_manager_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_allocator_smoke
    arcology-os/tests/systems/systems_arco_basic_allocator_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_region_policy_smoke
    arcology-os/tests/systems/systems_arco_basic_region_policy_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_region_allocator_smoke
    arcology-os/tests/systems/systems_arco_basic_region_allocator_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_prd_runtime_smoke
    arcology-os/tests/systems/systems_arco_basic_prd_runtime_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_virtual_region_smoke
    arcology-os/tests/systems/systems_arco_basic_virtual_region_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_page_table_smoke
    arcology-os/tests/systems/systems_arco_basic_page_table_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_page_table_geometry_smoke
    arcology-os/tests/systems/systems_arco_basic_page_table_geometry_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_exception_entry_smoke
    arcology-os/tests/systems/systems_arco_basic_exception_entry_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_shift_correctness_smoke
    arcology-os/tests/systems/systems_arco_basic_shift_correctness_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_large_frame_call_smoke
    arcology-os/tests/systems/systems_arco_basic_large_frame_call_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_breakpoint_recovery_smoke
    arcology-os/tests/systems/systems_arco_basic_breakpoint_recovery_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_gdt_reload_smoke
    arcology-os/tests/systems/systems_arco_basic_gdt_reload_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_emergency_stack_smoke
    arcology-os/tests/systems/systems_arco_basic_emergency_stack_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_timer_tick_smoke
    arcology-os/tests/systems/systems_arco_basic_timer_tick_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_loop_dispatch_smoke
    arcology-os/tests/systems/systems_arco_basic_loop_dispatch_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_block_storage_smoke
    arcology-os/tests/systems/systems_arco_basic_block_storage_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_blockio_disk_smoke
    arcology-os/tests/systems/systems_arco_basic_blockio_disk_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_multi_blockio_discovery_smoke
    arcology-os/tests/systems/systems_arco_basic_multi_blockio_discovery_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_gpt_image_smoke
    arcology-os/tests/systems/systems_arco_basic_gpt_image_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_gpt_sysvol_render_smoke
    arcology-os/tests/systems/systems_arco_basic_gpt_sysvol_render_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arcology_seed_ready_smoke
    arcology-os/tests/systems/systems_arcology_seed_ready_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_ps2_keyboard_driver_smoke
    arcology-os/tests/systems/systems_ps2_keyboard_driver_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_xhci_controller_init_smoke
    arcology-os/tests/systems/systems_xhci_controller_init_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_blockio_provider_smoke
    arcology-os/tests/systems/systems_arco_basic_blockio_provider_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_blockio_fat32_smoke
    arcology-os/tests/systems/systems_arco_basic_blockio_fat32_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_extent_tree_reflink_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_extent_tree_reflink_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_remount_reflink_sharing_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_remount_reflink_sharing_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_tree_scrub_coverage_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_tree_scrub_coverage_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_multi_attribute_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_multi_attribute_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_attribute_bound_fix_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_attribute_bound_fix_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_checkpoint_self_description_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_checkpoint_self_description_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_feature_negotiation_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_feature_negotiation_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_reserved_rows_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_reserved_rows_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_production_scale_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_production_scale_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_string_blob_attribute_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_string_blob_attribute_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_persist_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_persist_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_multi_sector_bitmap_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_multi_sector_bitmap_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_sysvol_persist_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_sysvol_persist_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_long_session_durability_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_long_session_durability_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_string_equality_smoke
    arcology-os/tests/systems/systems_arco_basic_string_equality_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_string_len_mid_smoke
    arcology-os/tests/systems/systems_arco_basic_string_len_mid_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_a_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_a_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_b_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_b_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_c_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_c_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_d_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_d_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_e_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_e_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_f_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_f_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_g_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_g_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_system_volume_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_system_volume_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_system_namespace_smoke
    arcology-os/tests/systems/systems_system_namespace_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_recovery_environment_smoke
    arcology-os/tests/systems/systems_recovery_environment_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_graphical_storage_tooling_smoke
    arcology-os/tests/systems/systems_graphical_storage_tooling_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_render_and_halt_smoke
    arcology-os/tests/systems/systems_render_and_halt_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_h_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_h_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_oid128_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_oid128_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_i_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_i_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_j_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_j_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_phase_k_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_phase_k_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_namespace_tree_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_namespace_tree_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_offset_io_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_offset_io_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_attribute_tree_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_attribute_tree_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
arco_add_script_test(
    systems_arco_basic_arcfs_health_model_smoke
    arcology-os/tests/systems/systems_arco_basic_arcfs_health_model_smoke.sh
    $<TARGET_FILE:ArcoFission>
    ${CMAKE_CURRENT_SOURCE_DIR}
)
