set(ARCO_GUI_BACKEND_AVAILABLE FALSE)
set(ARCO_GUI_BACKEND_SOURCE src/gui/stub_backend.cpp)

if(ARCO_ENABLE_GUI AND UNIX AND NOT APPLE)
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_check_modules(GLFW3 QUIET IMPORTED_TARGET glfw3)
        pkg_check_modules(PANGOCAIRO QUIET IMPORTED_TARGET pangocairo)
        pkg_check_modules(GTK3 QUIET IMPORTED_TARGET gtk+-3.0)
    endif()
    find_package(OpenGL QUIET)

    if(GLFW3_FOUND AND PANGOCAIRO_FOUND AND GTK3_FOUND AND OpenGL_FOUND)
        set(ARCO_GUI_BACKEND_AVAILABLE TRUE)
        set(ARCO_GUI_BACKEND_SOURCE src/gui/glfw_backend.cpp)
    endif()
endif()

if(ARCO_ENABLE_NETWORK)
    find_package(CURL QUIET)
endif()
